# Site
repository: IsraelAbebe/IsraelAbebe.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:path/

# Personal info
name: Israel A. Azime
title: PhD Candidate | Research Assistant
email: "se.israel.abebe [at] gmail [dot] com"
email2: "azime [at] cg.uni-saarland [dot] de"
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: https://israelabebe.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: Israel_Abebe
github_username:  IsraelAbebe
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: israel-abebe
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: PcAQRn0AAAAJ

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=PcAQRn0AAAAJ
- title: Hugging Face
  icon: assets/img/hf-logo-pirate.png
  url: https://huggingface.co/israel

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-159259301-1"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/img/ava.png
about_content: | # this will include new lines to allow paragraphs
  LLM reasoning, grounding, robustness, and evaluation using multilingual and cultural variation as a scientific lens.

  I am currently a PhD student and research assistant at [Saarland University](https://www.uni-saarland.de/en/home.html) supervised by [Prof. Dr.-Ing. Philipp Slusallek](https://graphics.cg.uni-saarland.de/people/slusallek.html) and [Prof. Dr. Dietrich Klakow](https://www.lsv.uni-saarland.de/people/dietrich-klakow/). With over four years of experience in the machine learning industry, I have worked in diverse applied research roles, including Applied Research Data Scientist at [Iquartic](https://iquartic.com/) and Applied ML Developer at [SingularityNet/iCog-Labs](https://singularitynet.io/).

  I hold an MSc in Mathematical Sciences – Machine Intelligence from [AIMS-AMMI](https://aimsammi.org/) and a Bachelor of Science in Software Engineering from [Addis Ababa Institute of Technology](http://www.aait.edu.et/). I am an active member of the [Masakhane](https://www.masakhane.io/), [ETHIO NLP](https://ethionlp.github.io/)  and [AI-Grid](https://ai-grid.org/en/) community.

  My research focuses on effective domain adaptation and evaluation methods for large language models (LLMs) in low-resource human and data languages. The overarching goal of my work is to advance the development of AI systems that are accurate, interpretable, robust, and culturally grounded, while remaining human-centered and contextually aware. I investigates how LLMs can better understand, reason, and communicate across linguistic, cultural, and structural boundaries, bridging the gap between human meaning and machine representation. Ultimately, my work aims to create socially aware and context-sensitive AI systems that perform reliably across diverse languages and data modalities.

content:
  - title: Education
    layout: list
    content:
      - layout: top
        title: Universität des Saarlandes, Saarbrücken, Germany
        sub_title: PhD candidate
        caption: "September 2022 – December 2026 [Expected]"
        description: |
          - Thesis: Understanding, Confusion, and Consequence of LLMs in Low Resource Languages.
          - Supervisor: Prof. Dr.-Ing. Philipp Slusallek and Prof. Dr. Dietrich Klakow.
      - layout: top
        title: African Institute for Mathematical Sciences, Accra, Ghana
        sub_title: Master of Science, Mathematical Sciences – Machine Intelligence
        caption: "October 2019 – March 2021"
        description: |
          - Thesis: Exploring Data Imbalance and Modality Bias in Hateful Memes.
          - Supervisor: Prof. Dr. Marcus Rohrbach.
      - layout: top
        title: Addis Ababa University, Addis Ababa, Ethiopia
        sub_title: Bachelor of Science, Software Engineering
        caption: "September 2012 – December 2017"
        description: |
          - Project: Amharic online handwriting recognition keyboard.
          - Supervisor: Dr. Natnael Argaw Wondimu
          - Recognition: Certification Of Recognition For Outstanding Graduation Project.

  - title: Experience
    layout: list
    content:
      - layout: top
        title: University of South Florida, Tampa, Florida
        sub_title: PhD Internship
        caption: "July 2025 – Present"
        description: |
          - Socio-Cultural Large Language Models and Low Resource Languages.
          - Guest Lecture: University of South Florida.
      - layout: top
        title: Universität des Saarlandes, Saarbrücken, Germany
        sub_title: Research Assistant | HPC cluster support
        caption: "September 2022 – Present"
        description: |
          - Conducting research in NLP, Multimodal learning, and AI/ML.
          - Managing HPC clusters and multi-GPU model training.
          - Providing HPC-related training and technical support.
      - layout: top
        title: iQuartic, New Wave, Maryland, USA
        sub_title: Applied Research Data Scientist
        caption: "March 2021 – October 2022"
        description: |
          - Developed AI solutions for automated risk adjustment, transitioning pipelines to in-house solutions.
          - Built end-to-end pipelines for medical OCR, spell checking, and ICD code extraction.
          - Managed data collection, model building, deployment, and testing phases.
      - layout: top
        title: SingularityNet, Icog-Labs, Addis Ababa, Ethiopia
        sub_title: Applied ML Developer
        caption: "June 2017 – August 2022"
        description: |
          - Developed CNN, GAN, and VAE models for fake news and plant disease detection (97–98% accuracy).
          - Implemented web recommendation systems using Doc2Vec and DeepCTR.
          - Built large-scale image retrieval systems and conducted visual graph analytics.
      - layout: top
        title: Icog-Labs Software Consultancy, Addis Ababa, Ethiopia
        sub_title: Internship - Junior Programmer
        caption: "Jan 2015 – May 2017"
        description: |
          - Developed (YANETU), an AI-powered teaching assistant for children.
          - Built product components using Unity3D, Blender, and OpenCog NLP.

  - title: Publications
    layout: publications
    content: []

  - title: Projects
    layout: projects
    content: []

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  "update.py"
  ]
